### PR TITLE
Update OrderItem.php

### PR DESCRIPTION
**Pull request by gulaandrij**
fixes the wrong setting weight of the ordered item

### CODE REVIEW

**Comment by gulaandrij** [comment]
ping @zack6849

**Comment by zack6849** [comment]
Could you explain why this is "wrong"?
I'm not the original author of this code, this is a fork, but I'm not sure I understand why this is better or why the original is wrong, there's not even a "weight" property on the OrderItem Object, so why would you set one? 

If you're trying to bring this in line with the same functionality of the Order model, that'd make sense, but then we should be declaring all of those as properties of the Order Item, no?

The base model class looks (to me) like when you construct it with attributes, it assigns them to a property anyways

Is the issue that you're using order item but trying to update the weight, and the update isn't reflected in the magic property it declares, or something of that nature?

Thanks,

**Comment by gulaandrij** [comment]
the main problem that 'weight' is set to the attribute array and not send to API

before fix
image

after fix
image

**Comment by gulaandrij** [comment]
also as you can see here https://www.shipstation.com/developer-api/#/reference/model-orderitem Order Item object has 'weight' attribute

**Comment by zack6849** [comment]
I also went ahead and refactored all the other attribute arrays as properties, could you confirm this is working as expected? If so, i'll tag a new release

Thanks @gulaandrij !

**Comment by gulaandrij** [comment]
tnx, I'll check

**Comment by zack6849** [comment]
@gulaandrij did you ever figure out if the code in master fixed your problems?

**Pull request merged**
